defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 25
  username: postgres
  host: 127.0.0.1

development:
  <<: *defaults
  database: test_app_development

test:
  <<: *defaults
  database: test_app_test

staging:
  <<: *defaults
  database: test_app_staging

production:
  <<: *defaults
  database: test_app_production
